import "./globals.css";
import { CartProvider } from "../components/CartContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <nav style={{ padding: '1rem', borderBottom: '1px solid #eee', marginBottom: '2rem', display: 'flex', gap: '2rem' }}>
            <a href="/">Home</a>
            <a href="/products">Products</a>
            <a href="/cart">Cart</a>
          </nav>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
